In [ ]:
NumPy v2.3 Manual: https://numpy.org/doc/stable/user/quickstart.html

In [ ]:
# Array Creation

# 1
    a = np.arange(6)                    # [0 1 2 3 4 5]
    b = np.arange(12).reshape(4, 3)     # 4x3 matrix
    c = np.arange(24).reshape(2, 3, 4)  # Two 3x4 matrices
    a = np.arange(10)**3                # [  0   1   8  27  64 125 216 343 512 729]

# 2
    # arange(start, stop, step) (like range, accepts floats).
    a = np.arange(10, 30, 5)  # [10 15 20 25]   
    b = np.arange(0, 2, 0.3)  # [0.  0.3 0.6 0.9 1.2 1.5 1.8]

# 3
    np.zeros((3, 4))  # All zeros
    np.ones((2, 3, 4), dtype=np.int16)  # 3D array of ones
    np.empty((2, 3))  # Random values (may vary)

# 4
    # Explicit dtype
    c = np.array([[1, 2], [3, 4]], dtype=complex)  # array([[1.+0.j 2.+0.j] [3.+0.j 4.+0.j]])

# 5
    # BASIC
    a = np.array([2, 3, 4])        
    b = np.array([1.2, 3.5, 5.1]) 
    
# 5
    # BASIC 
    b = np.array([(1.5, 2, 3), (4, 5, 6)])  # 2D array([[1.5 2. 3.] [4. 5. 6.]])

# 6
    np.linspace(0, 2, 9)  # array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])
    x = np.linspace(0, 2 * np.pi, 100)
    f = np.sin(x)

In [ ]:
Accessing 1D array:

    arr = np.array([1, 2, 3, 4])    # Output: 1
    print(arr[0])

Acessing 2D array:

    arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])    # Output: 2
    print('2nd element on 1st row: ', arr[0, 1])

Acessing 3D array:

    arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])    # Output: 6
    print(arr[0, 1, 2])

Negative Indexing: 

    arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])       # Output: 10
    print('Last element from 2nd dim: ', arr[1, -1])

In [ ]:
Slicing arrays:   [start:end:step]

    Slicing 1D array:
    
        arr = np.array([1, 2, 3, 4, 5, 6, 7])
        
        print(arr[1:5])      # Output: [2 3 4 5]
        print(arr[4:])       # Output: [5 6 7]
        print(arr[:4])       # Output: [1 2 3 4]
        print(arr[-3:-1])    # Output: [5 6]
        print(arr[1:5:2])    # Output: [2 4]
        print(arr[::2])      # Output: [1 3 5 7]
        arr[:6:2] = 1000     # [1000    2 1000    4 1000    6    7]
        print(arr[::-1])     # [   7    6 1000    4 1000    2 1000]

    Slicing 2D array:

        arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
        
        print(arr[1, 1:4])      # Output: [7 8 9]
        print(arr[0:2, 2])      # Output: [3 8]
        print(arr[0:2, 1:4])    # Output: [[2 3 4] [7 8 9]]   ( This will return a 2-D array )

In [ ]:
def f(x, y): return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)  # 5x4 array
print(b)

# Output

[[ 0  1  2  3]                The function f(x, y) = 10 * x + y is applied to each position (x, y):
 [10 11 12 13]                At (0, 0): f(0, 0) = 10 * 0 + 0 = 0
 [20 21 22 23]                At (0, 1): f(0, 1) = 10 * 0 + 1 = 1
 [30 31 32 33]                At (0, 2): f(0, 2) = 10 * 0 + 2 = 2
 [40 41 42 43]]               At (0, 3): f(0, 3) = 10 * 0 + 3 = 3
                              At (1, 0): f(1, 0) = 10 * 1 + 0 = 10
                              At (1, 1): f(1, 1) = 10 * 1 + 1 = 11
                              And so on...
# Slicing 
print(b[2, 3])     # 23

print(b[0:5, 1])   # Second column: [ 1 11 21 31 41]
print(b[:, 1])     # Same as above

print(b[1:3, :])    # Rows 2-3

In [ ]:
# Ellipsis (...): Fills remaining dimensions (e.g., c[1, ...] = c[1, :, :]).

c = np.array([[[0,1,2],[10,12,13]], [[100,101,102],[110,112,113]]])  # (2,2,3) 

print(c[1, ...])  # Second "layer"   --> So in block 1 select all rows and columns 

# Output 
[[100 101 102]
 [110 112 113]]

print(c[..., 2])  # Last element per subarray

#Output:
[[  2  13]
 [102 113]]

In [ ]:
# Key Attributes of ndarray

ndim      Number of axes (dimensions).
shape     Tuple of integers for size per dimension (e.g., (n, m) for matrix; length = ndim).
size      Total elements (product of shape).
dtype     Element type (e.g., numpy.int32, numpy.int16, numpy.float64).
itemsize  Bytes per element (e.g., 8 for float64). Equivalent to dtype.itemsize.
data      Buffer of elements (rarely used directly; use indexing).


a = np.arange(15).reshape(3, 5)

print(a.dtype.type)      # <class 'numpy.int32'>
print(a.dtype)           # int32
print(type(b))           # <class 'numpy.ndarray'>

print(a)                 # array([[ 0,  1,  2,  3,  4], [ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])

print(a.shape)           # (3, 5)
print(a.size)            # 15
print(a.ndim)            # 2

print(a.itemsize)        # 4  --> returns the size (in bytes) of each element of a NumPy array.

In [ ]:
# Basic Operations 

a = np.array([[1, 1], [0, 1]])
b = np.array([[2, 0], [3, 4]])

print(a @ b)             #  [[5 4] [3 4]]  @ --> Matrix Product
print(a.dot(b))          # Same i.e [[5 4] [3 4]]

print(a - b)             # [[-1  1] [-3 -3]]

print(b ** 2)            # [[ 4  0] [ 9 16]]

print(10 * np.sin(a))    # Elementwise sin [[8.41470985 8.41470985] [0.         8.41470985]]

print(a < 35)            # [[ True  True] [ True  True]]  --> Returns boolean array

print(a * b)             # [[2 0] [0 4]]

print(np.add(a,b))       # [[3 1] [3 5]]

# axis = 0 --> across rows
# axis = 1 --> across columns

c = np.array([[1,2],[3,4]])

print(np.exp(c))          # [[ 2.71828183  7.3890561 ] [20.08553692 54.59815003]]

print(np.sqrt(c))         # [[1.         1.41421356] [1.73205081 2.        ]]

print(c.sum(axis = 0))    # Row sums: [4 6]

print(c.min(axis = 1))     # Column mins: [1 3]

print(c.cumsum(axis = 1))  # Cumulative column sums  [[1 3] [3 7]]

In [ ]:
a = np.arange(12)**2
i = np.array([1,1,3,8,5])
j = np.array([[3,4],[9,7]])

a[i]  # [1,1,9,64,25]
a[j]  # [[9,16],[81,49]]

a = np.arange(12).reshape(3,4)
print(a)
i = np.array([[0,1],[1,2]])
j = np.array([[2,1],[3,3]])
print(i)
print(j)
print(a[i,j])  # [[2,5],[7,11]]

In [ ]:
b = np.arange(1,7).reshape(2,3)

for row in b: print(row)
    
for element in b.flat: print(element)
    
print(b.flatten())

for i in b: print(i**(1/3.))  # Cube roots (may vary slightly due to float precision)

# Output 
[1 2 3]
[4 5 6]

1
2
3
4
5
6

[1 2 3 4 5 6]

[1.         1.25992105 1.44224957]
[1.58740105 1.70997595 1.81712059]

In [ ]:
# Boolean Making in Numpy

y_train = np.array([0,  0, 0, 1, 1, 1])

pos = y_train == 1
neg = y_train == 0

print(pos)     # [False False False  True  True  True]
print(neg)     # [ True  True  True False False False]
print(y_train[pos])  # [1 1 1]
print(y_train[neg])  # [0 0 0]

In [ ]:





Shape manipulation, 
Copies and views
Functions and Methods Overview
Less basic: Broadcasting rules
Advanced indexing and index tricks











In [ ]:
Data Types


Default    NumPy

integer    i - integer
           u - unsigned integer

float      f - float

string     S - string
           U - unicode string

complex    c - complex float

boolean    b - boolean

           m - timedelta
           M - datetime

           O - object

           V - fixed chunk of memory for other type ( void )